# Generated by Django 4.0.4 on 2022-05-10 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('GM', 'Games'), ('MC', 'Music')], default='MC', max_length=2)),
                ('genre_ru', models.CharField(choices=[('GM', 'Games'), ('MC', 'Music')], default='MC', max_length=2, null=True)),
                ('genre_en', models.CharField(choices=[('GM', 'Games'), ('MC', 'Music')], default='MC', max_length=2, null=True)),
                ('photo', models.ImageField(upload_to='static/imgs')),
                ('title', models.CharField(blank=True, max_length=15, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=15, null=True)),
                ('title_en', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField(max_length=100)),
                ('description_ru', models.TextField(max_length=100, null=True)),
                ('description_en', models.TextField(max_length=100, null=True)),
                ('creation', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('likes', models.ManyToManyField(related_name='post_like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=1000)),
                ('user', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100)),
                ('creation', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photojournal.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
