# Generated by Django 4.0.4 on 2022-05-10 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(upload_to='accounts/static/images')),
                ('username', models.CharField(max_length=12)),
                ('username_ru', models.CharField(max_length=12, null=True)),
                ('username_en', models.CharField(max_length=12, null=True)),
            ],
        ),
    ]
